name: Build and Deploy

on:
  push:
    branches: [main]
env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  VPS_DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Шаг 3: Собираем бэкенд (Express + TypeORM)
      - name: Build Backend
        run: |
          npm ci
          npm run build

      # Шаг 4: Собираем фронтенд (Angular)
      - name: Build Frontend
        working-directory: ./client
        run: |
          npm ci
          npm run build -- --configuration production

    # Шаг 5: Создаем артефакты
      - name: Create deployment artifacts
        run: |
          mkdir -p artifacts/build
          cp -r build package.json package-lock.json artifacts/build/
          mkdir -p artifacts/client/dist/client
          cp -r client/dist/client/* artifacts/client/dist/client/

    # Шаг 6: Загружаем артефакты на VPS
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "artifacts/*"
          target: ${{ secrets.VPS_DEPLOY_PATH }}
          strip_components: 1